/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ecc160",
        "on-secondary-container": "#775900",
        "surface-variant": "#e2e3e0",
        "secondary": "#785a00",
        "background": "#f9f9f6",
        "inverse-on-surface": "#f1f1ee",
        "on-secondary": "#ffffff",
        "primary": "#38656f",
        "surface-dim": "#dadad7",
        "tertiary-fixed": "#ffd8ea",
        "on-surface": "#1a1c1b",
        "on-tertiary-fixed": "#330d25",
        "surface-bright": "#f9f9f6",
        "inverse-surface": "#2f312f",
        "surface-container-high": "#e8e8e5",
        "outline-variant": "#c0c8ca",
        "tertiary-container": "#f2b5d4",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a0ced9",
        "primary-container": "#a0ced9",
        "on-primary-container": "#2b5962",
        "outline": "#71787a",
        "tertiary": "#804f6a",
        "error": "#ba1a1a",
        "surface-tint": "#38656f",
        "on-primary-fixed-variant": "#1d4d56",
        "on-primary-fixed": "#001f25",
        "surface-container": "#eeeeeb",
        "error-container": "#ffdad6",
        "on-background": "#1a1c1b",
        "secondary-fixed": "#ffdf9d",
        "on-secondary-fixed-variant": "#5b4300",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed16e",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2e3e0",
        "on-tertiary-container": "#73445e",
        "primary-fixed": "#bceaf6",
        "tertiary-fixed-dim": "#f2b5d4",
        "surface-container-low": "#f4f4f1",
        "surface": "#f9f9f6",
        "on-tertiary-fixed-variant": "#653852",
        "on-secondary-fixed": "#251a00",
        "on-surface-variant": "#40484a",
        "inverse-primary": "#a0ced9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "shadow-offset": "6px",
        "xs": "8px",
        "base": "4px",
        "sm": "16px",
        "border-width": "4px",
        "lg": "40px",
        "xl": "64px"
      },
      fontFamily: {
        "h1-mobile": ["FatFrank", "sans-serif"],
        "body-lg": ["MencoBlack", "sans-serif"],
        "body-md": ["MencoBlack", "sans-serif"],
        "h1": ["FatFrank", "sans-serif"],
        "h3": ["FatFrank", "sans-serif"],
        "h2": ["FatFrank", "sans-serif"],
        "label-bold": ["MencoBlack", "sans-serif"]
      },
      fontSize: {
        "h1-mobile": ["32px", { lineHeight: "1.1", fontWeight: "normal" }],
        "body-lg": ["20px", { lineHeight: "1.5", fontWeight: "normal" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "normal" }],
        "h1": ["48px", { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "normal" }],
        "h3": ["28px", { lineHeight: "1.2", fontWeight: "normal" }],
        "h2": ["36px", { lineHeight: "1.2", fontWeight: "normal" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "normal" }]
      }
    },
  },
  plugins: [],
}
